server:
  port: 8080

spring:
  application:
    name: login_project
  datasource:
    url: jdbc:postgresql://localhost:5432/login_project
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

security-project:
  secret-key: ${SECRET_KEY}

jwt:
  secret: ${}

email-service:
  from: ${EMAIL_FROM}

front-end:
  url: ${FRONT_END_URL}

swagger:
  api:
    title: Login backend
    description: This backend handles user login, registration, and token management. It securely encrypts user passwords using AES-256 encryption and ensures secure authentication and authorization through token-based mechanisms.